import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

# decorations = "Buttonless"

opacity = 1
blur = true

# option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
